spring:
  batch:
    initialize-schema: never
  application:
    name: BATCH
  datasource:
    url: jdbc:mysql://localhost:3306/batch?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver